- README.md
repeat of "security" topic removed
> changed ReadMe file

- README.md
> Added EMOJI to Read Me file

- src/Commands/CheckEvent.php
- src/Commands/CheckGate.php
- src/Commands/CheckImports.php
- src/Commands/CheckPsr4.php
- src/Commands/CheckRoute.php
- src/Commands/CheckView.php
- src/ErrorPrinter.php
- src/Traits/LogsErrors.php
Currently if you run a command and everything is correct, the console does not give the user any feedback so this PR aims to give the user a feedback.
I ran` php artisan check:all` and i got this feedback with this PR.
> Added command feedback

- src/Commands/CheckRoute.php
- src/ErrorPrinter.php
- src/PendingObjects/PendingError.php
when use check:routes , print "All route are correct!" even if has errors
> bug fix for check:routes

- src/Checks/CheckRouteCalls.php
- src/Commands/CheckRoutes.php
- src/Commands/CheckViews.php
- src/ErrorPrinter.php
- src/LaravelMicroscopeServiceProvider.php
The real deal is on the last commit, the first ones where just some house keeping.
So i was having an issue with `check:views`, it would check even the routes but logged successful but it had route problems. 
Just made sure we log errors at the appropriate moment
> Fix check views

- src/Commands/CheckActionComments.php
- src/Commands/CheckAll.php
- src/Commands/CheckBadPractice.php
- src/Commands/CheckCompact.php
- src/Commands/CheckDD.php
- src/Commands/CheckEarlyReturns.php
- src/Commands/CheckEvents.php
- src/Commands/CheckExtractBladeIncludes.php
- src/Commands/CheckGates.php
- src/Commands/CheckImports.php
- src/Commands/CheckPsr4.php
- src/Commands/CheckRoutes.php
- src/Commands/CheckViews.php
- src/Commands/ClassifyStrings.php
This pull request fixes issue #59.
> Add exit code to all check commands

- README.md
This is awesome package and very useful. i create a one video tutorial of this package. please add it in doc. so, it helpful to people. Thanks for this great package for community.
> doc(readme): Video tutoral link add

- README.md
I found the package is useful for the Laravel community. I was reading readme and found some spellings as well as grammatical mistakes. Here is the PR to correct spelling and grammatical mistakes.
PS: it is my first PR If something is not up to the standard please comment I will make the change.
> correct spellings and grammatical mistakes

- src/Commands/CheckAll.php
> Fix the force option does not exists bug

- src/Commands/CheckEndIf.php
> text update for endif command

- .travis.yml
- src/Analyzers/ClassReferenceFinder.php
For `ci` purposes please accept this PR and then on your [dashboard](https://travis-ci.com/dashboard), grant access to this service for accessing to your repository.
> add travis feature

- src/SearchReplace/PatternRefactorings.php
we got an exception while running `PHP artisan search_replace` because of "Token Comaper Class Has been changed to Finder"
> class TokenCompare changed to Finder

- src/ErrorReporters/ErrorPrinter.php
a little refactor on ErrorPirinter class
> bit refactor ErrorPrinter class

- src/Checks/FacadeDocblocks.php
some times we have a bad facade definition  we should return a better error message rather than Exception and die;
> fix error on bad facade definision

- composer.json
I got an error when I tried to run the tests with php(8.1.3) . I fixed it by updating several packages.
> update orchestra/testbench and phpunit/phpunit

- tests/FunctionCallTest.php
- tests/stubs/function_test/some_function.sub
Find dd function with FunctionCallTest
> first test for FunctionCallTest

- README.md
fix some bug in markdown
change from this
|3|`php artisan check:psr4 {-s|--nofix} `|
to
|3|`php artisan check:psr4 {-s\|--nofix} `|
> Bug-fix Readme

- src/SearchReplace/PatternRefactorings.php
Check in PatternRefactorings class for pattern
for before pull request => https://github.com/imanghafoori1/laravel-microscope/pull/231
> fix error undefined array key 0 for search_replace

- README.md
Just fixed typo in word usefull
> Fix typo in usefull

- src/CheckClassReferencesAreValid.php
- src/Checks/CheckClassReferences.php
- src/Checks/CheckImport.php
- src/Commands/CheckImports.php
> Complete the information in the overall section on check imports command

- src/LaravelPaths/LaravelPaths.php
use the databasePath method in the right way. Am I allowed to add some tests for LaravelPaths\LaravelPaths.php or other sections?
> refactor: use the databasePath method in the right way

- .github/workflows/run-tests.yml
After merging this PR, tests will automatically execute for any new commits or PRs.
To activate this workflow, follow these steps:
- Merge the PR.
- Navigate to the "Actions" tab and press "Enable actions for this repository".
- Submit a new PR or commit a new change to initiate the testing process.
> Add Github workflow to run test

- src/Features/CheckImports/CheckImportReporter.php
Refactoring the method `printFileCounts` for better readability and maintenance.
> Refactor printFileCounts method

- README.md
> Fix items of check:generate in readme file
